# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
filter = {except_tables = ["_prisma_migrations"]}

[migrations_directory]
dir = "migrations"
